#!/usr/bin/env bash
# Generate SHA-256 checksums for critical bootstrap files.
# Run on a device after first install, then paste the output into
# BootstrapInstaller.kt's EXPECTED_CHECKSUMS map.
#
# Usage:
#   ./scripts/generate_bootstrap_checksums.sh [PREFIX]
#
# If PREFIX is not given, defaults to /data/data/com.nvterm/files/usr
#
# Output format: Kotlin map entries ready to paste into EXPECTED_CHECKSUMS.

set -euo pipefail

PREFIX="${1:-/data/data/com.nvterm/files/usr}"

CRITICAL_FILES=(
    "bin/bash"
    "bin/sh"
    "bin/login"
    "lib/libtermux-exec-linker-ld-preload.so"
    "lib/libtermux-exec-ld-preload.so"
    "lib/libtermux-exec.so"
)

echo "// Generated by: scripts/generate_bootstrap_checksums.sh"
echo "// Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "// Device: $(uname -m)"
echo ""
echo "private val EXPECTED_CHECKSUMS = mapOf("

for file in "${CRITICAL_FILES[@]}"; do
    full_path="$PREFIX/$file"
    if [ -f "$full_path" ]; then
        checksum=$(sha256sum "$full_path" | cut -d' ' -f1)
        echo "    \"$file\" to \"$checksum\","
    else
        echo "    // WARNING: $file not found at $full_path"
        echo "    \"$file\" to \"0000000000000000000000000000000000000000000000000000000000000000\","
    fi
done

echo ")"