package com.novaterm.core.bootstrap

import android.content.Context
import android.system.Os
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.InputStream
import java.math.BigInteger
import java.security.MessageDigest
import java.security.NoSuchAlgorithmException
import java.util.zip.ZipInputStream

/**
 * Installs the terminal bootstrap environment on first launch.
 *
 * The bootstrap is a ZIP archive (~30MB) containing bash, coreutils, apt,
 * termux-exec, and other essential Unix tools compiled for Android arm64.
 * It is embedded in the APK as a native library (libtermux-bootstrap.so)
 * via the .incbin assembly directive.
 *
 * Installation process:
 * 1. Load ZIP bytes from the native library
 * 2. Extract to a staging directory (usr-staging/)
 * 3. Parse SYMLINKS.txt and create symlinks
 * 4. Set executable permissions on binaries
 * 5. Atomic rename: staging → prefix (prevents partial installs)
 *
 * Architecture inspired by Termux's TermuxInstaller.java (GPLv3),
 * but rewritten from scratch in Kotlin for NovaTerm.
 */
class BootstrapInstaller(private val context: Context) {

    sealed class State {
        data object Idle : State()
        data class Extracting(val progress: Float, val currentFile: String) : State()
        data object Finalizing : State()
        data object Done : State()
        data class Error(val message: String) : State()
    }

    private val _state = MutableStateFlow<State>(State.Idle)
    val state: StateFlow<State> = _state.asStateFlow()

    private val filesDir: String get() = context.filesDir.absolutePath

    /** The prefix directory where packages are installed ($PREFIX). */
    val prefixDir: File get() = File(filesDir, "usr")

    /** Whether the bootstrap has been installed (bash or sh exists). */
    // Use exists() NOT canExecute() — W^X makes canExecute() return false
    val isBootstrapped: Boolean
        get() = File(prefixDir, "bin/bash").exists() ||
                File(prefixDir, "bin/sh").exists()

    /**
     * Calculate SHA-256 checksum for a file.
     * @param filePath Path to the file
     * @return Hex string representation of SHA-256 checksum
     */
    private fun calculateFileChecksum(filePath: String): String? {
        return try {
            val inputStream = FileInputStream(filePath)
            val md = MessageDigest.getInstance("SHA-256")
            val buffer = ByteArray(8192)
            var length: Int
            while (inputStream.read(buffer).also { length = it } != -1) {
                md.update(buffer, 0, length)
            }
            inputStream.close()
            val digest = md.digest()
            String.format("%064x", BigInteger(1, digest))
        } catch (e: Exception) {
            Log.e(TAG, "Failed to calculate checksum for $filePath", e)
            null
        }
    }

    /**
     * Verify integrity of critical bootstrap files.
     *
     * Two verification levels:
     * 1. **Checksum** (when available): SHA-256 match against EXPECTED_CHECKSUMS.
     *    Checksums are generated by `generate_bootstrap_checksums.sh` on CI/device.
     * 2. **Fallback** (when checksum is placeholder "0...0"): verify file exists,
     *    has non-zero size, and is executable (for binaries).
     *
     * @param prefix The bootstrap prefix directory
     * @return true if all critical files pass verification
     */
    private fun verifyBootstrapIntegrity(prefix: String): Boolean {
        val prefixDir = File(prefix)

        for ((filePath, expectedChecksum) in EXPECTED_CHECKSUMS) {
            val file = File(prefixDir, filePath)
            if (!file.exists()) {
                Log.e(TAG, "Critical file missing: $filePath")
                return false
            }

            // Placeholder checksum → fall back to existence + size + exec check
            if (expectedChecksum.startsWith("0000")) {
                if (file.length() == 0L) {
                    Log.e(TAG, "Critical file is empty: $filePath")
                    return false
                }
                // Binaries must be executable (W^X bypass: use exists, not canExecute)
                if (filePath.startsWith("bin/") && !file.exists()) {
                    Log.e(TAG, "Binary not accessible: $filePath")
                    return false
                }
                Log.i(TAG, "Verified $filePath: exists, ${file.length()} bytes (no checksum)")
                continue
            }

            // Full SHA-256 checksum verification
            val actualChecksum = calculateFileChecksum(file.absolutePath)
            if (actualChecksum == null) {
                Log.e(TAG, "Failed to compute checksum for $filePath")
                return false
            }
            if (!actualChecksum.equals(expectedChecksum, ignoreCase = true)) {
                Log.e(TAG, "Checksum mismatch for $filePath. Expected: $expectedChecksum, Got: $actualChecksum")
                return false
            }
            Log.i(TAG, "Verified $filePath: checksum OK")
        }

        return true
    }

    /**
     * Install the bootstrap if not already present. Safe to call multiple times.
     * Returns true if bootstrap is ready (already installed or just installed).
     */
    suspend fun installIfNeeded(): Boolean {
        if (isBootstrapped) {
            _state.value = State.Done
            return true
        }
        return install()
    }

    /**
     * Force (re)installation of the bootstrap.
     */
    suspend fun install(): Boolean = withContext(Dispatchers.IO) {
        try {
            _state.value = State.Extracting(0f, "Loading...")

            // 0. Check available storage (bootstrap needs ~100MB)
            val availableBytes = File(filesDir).freeSpace
            val requiredBytes = 100L * 1024 * 1024 // 100MB
            if (availableBytes < requiredBytes) {
                val availableMB = availableBytes / 1024 / 1024
                Log.e(TAG, "Insufficient storage: ${availableMB}MB available, need 100MB")
                _state.value = State.Error("Insufficient storage. Need at least 100MB free (${availableMB}MB available).")
                return@withContext false
            }

            // 1. Resolve ZIP source — prefer streaming from assets (avoids 30MB in-memory peak).
            //    Fall back to JNI native library only if the asset is absent.
            val zipStreamProvider: () -> InputStream
            val assetName = "bootstrap-aarch64.zip"
            val hasAsset = try {
                context.assets.open(assetName).close(); true
            } catch (_: Exception) { false }

            if (hasAsset) {
                zipStreamProvider = { context.assets.open(assetName) }
            } else {
                Log.i(TAG, "Bootstrap not in assets, trying native library")
                val zipBytes = try {
                    // Fallback: JNI returns a ByteArray (unavoidable memory load for this path)
                    NativeBootstrap.getZip().also { b ->
                        Log.i(TAG, "Bootstrap ZIP loaded from native: ${b.size / 1024 / 1024} MB")
                    }
                } catch (linkEx: UnsatisfiedLinkError) {
                    Log.e(TAG, "No bootstrap found in assets or native library", linkEx)
                    _state.value = State.Error("Bootstrap not available.")
                    return@withContext false
                }
                zipStreamProvider = { zipBytes.inputStream() }
            }

            // 2. Count entries for progress (first streaming pass — no large buffer retained)
            var totalEntries = 0
            zipStreamProvider().use { ZipInputStream(it).use { z -> while (z.nextEntry != null) totalEntries++ } }
            Log.i(TAG, "Bootstrap ZIP: $totalEntries entries")

            // 3. Clean staging directory
            val stagingDir = File(filesDir, "usr-staging")
            stagingDir.deleteRecursively()
            stagingDir.mkdirs()

            // 4. Extract ZIP (second streaming pass)
            val symlinks = mutableListOf<Pair<String, String>>()
            zipStreamProvider().use { extractZip(ZipInputStream(it), stagingDir, symlinks, totalEntries) }

            // 5. Set permissions
            _state.value = State.Finalizing
            setExecutePermissions(stagingDir)

            // 5. Atomic swap: staging → prefix
            val oldPrefix = File(filesDir, "usr-old")
            oldPrefix.deleteRecursively()
            if (prefixDir.exists()) {
                prefixDir.renameTo(oldPrefix)
            }
            if (!stagingDir.renameTo(prefixDir)) {
                // Restore old prefix on failure
                oldPrefix.renameTo(prefixDir)
                throw RuntimeException("Failed to rename staging directory to prefix")
            }
            oldPrefix.deleteRecursively()

            // 6. Create symlinks with patched targets (com.termux → com.nvterm in paths)
            val patchedSymlinks = symlinks.map { (target, link) ->
                target.replace("com.termux", "com.nvterm") to link
            }
            createSymlinks(patchedSymlinks, prefixDir)

            // 7. Validate critical files exist (after symlinks, so sh→bash resolves)
            val criticalBinaries = listOf("bin/bash", "bin/sh", "bin/login", "bin/apt", "bin/dpkg")
            val missing = criticalBinaries.filter { !File(prefixDir, it).exists() }
            if (missing.isNotEmpty()) {
                throw RuntimeException("Bootstrap extraction incomplete — missing: ${missing.joinToString()}")
            }

            // 8. Ensure required directories exist (apt, dpkg, cache)
            val requiredDirs = listOf(
                "tmp",
                "etc/apt/apt.conf.d",
                "etc/apt/preferences.d",
                "etc/apt/sources.list.d",
                "etc/apt/trusted.gpg.d",
                "var/lib/apt/lists/partial",
                "var/lib/dpkg/info",
                "var/lib/dpkg/triggers",
                "var/lib/dpkg/updates",
                "var/log/apt",
            )
            for (dir in requiredDirs) File(prefixDir, dir).mkdirs()

            // Also create apt cache outside $PREFIX (where libapt-pkg expects it)
            val cacheDir = File(context.cacheDir, "apt/archives/partial")
            cacheDir.mkdirs()

            // 9. Write apt sources.list (Termux package repository)
            //    Without this, apt update fails with "no sources" and no packages can be installed.
            val sourcesList = File(prefixDir, "etc/apt/sources.list")
            if (!sourcesList.exists()) {
                sourcesList.writeText(
                    "deb https://packages-cf.termux.dev/apt/termux-main stable main\n"
                )
                Log.i(TAG, "Wrote apt sources.list → Termux main repo")
            }

            // 10. Ensure dpkg status files exist
            File(prefixDir, "var/lib/dpkg/available").apply { if (!exists()) createNewFile() }
            File(prefixDir, "var/lib/dpkg/status").apply { if (!exists()) createNewFile() }

            // 11. Patch login script to export TMPDIR (Claude Code needs this).
            //     Android's /tmp is not writable by apps. Node.js os.tmpdir()
            //     reads TMPDIR env var, so we must ensure it's set before any
            //     child process starts.
            patchLoginScript(prefixDir)

            // 12. Install dpkg wrapper that patches .deb paths on install.
            //     Termux .debs have /data/data/com.termux/ hardcoded in data.tar.
            //     Since com.nvterm == com.termux in length, sed binary patch works.
            installDpkgWrapper(prefixDir)

            // 12. Copy GPG keys to trusted.gpg.d if they exist in share/
            val keyringDir = File(prefixDir, "share/termux-keyring")
            val trustedDir = File(prefixDir, "etc/apt/trusted.gpg.d")
            if (keyringDir.isDirectory) {
                keyringDir.listFiles()?.filter { it.extension == "gpg" }?.forEach { key ->
                    val dest = File(trustedDir, key.name)
                    if (!dest.exists()) key.copyTo(dest)
                }
                Log.i(TAG, "Installed ${trustedDir.listFiles()?.size ?: 0} GPG keys")
            }

            // 13. Replace Termux MOTD with NovaTerm branding
            replaceMotd(prefixDir)

            // 14. Copy setup scripts from assets (Claude Code auto-install, etc.)
            copyAssetScript("setup-claude.sh", File(prefixDir, "bin/setup-claude"))

            _state.value = State.Done
            Log.i(TAG, "Bootstrap installation complete: ${prefixDir.absolutePath}")
            // 23. Verify critical file integrity
            if (!verifyBootstrapIntegrity(prefixDir.absolutePath)) {
                Log.e(TAG, "Bootstrap integrity verification failed!")
                // Clean up on verification failure
                cleanUpFailedBootstrap(prefixDir.absolutePath)
                return@withContext false
            }

            // Diagnostic: verify critical files exist
            val criticalFiles = listOf(
                "bin/bash", "bin/sh", "bin/login",
                "lib/libnvterm-exec-linker-ld-preload.so",
                "lib/libnvterm-exec-ld-preload.so",
                "lib/libnvterm-exec.so",
                "lib/libnvterm-core_nos_c_tre.so",
                "lib/libnvterm-core_nos_cxx_tre.so",
                // Also check old names for backward compatibility
                "lib/libtermux-exec-linker-ld-preload.so",
                "lib/libtermux-exec-ld-preload.so",
                "lib/libtermux-exec.so",
                "lib/libtermux-core_nos_c_tre.so",
                "lib/libtermux-core_nos_cxx_tre.so",
            )
            for (f in criticalFiles) {
                val file = File(prefixDir, f)
                Log.i(TAG, "  $f: exists=${file.exists()} size=${if (file.exists()) file.length() else -1}")
            }
            true
        } catch (e: Exception) {
            Log.e(TAG, "Bootstrap installation failed", e)
            _state.value = State.Error(e.message ?: "Installation failed")
            // Clean up staging on failure
            File(filesDir, "usr-staging").deleteRecursively()
            false
        }
    }

    // ── ZIP extraction ────────────────────────────────────

    private fun extractZip(
        zis: ZipInputStream,
        targetDir: File,
        symlinks: MutableList<Pair<String, String>>,
        totalEntries: Int,
    ) {
        var extracted = 0
        var entry = zis.nextEntry
        while (entry != null) {
            val name = entry.name

            when {
                name == "SYMLINKS.txt" -> {
                    // Format: target←link (Unicode left arrow as delimiter)
                    val content = zis.readBytes().toString(Charsets.UTF_8)
                    content.lines()
                        .filter { "←" in it }
                        .forEach { line ->
                            val parts = line.split("←", limit = 2)
                            if (parts.size == 2) {
                                symlinks.add(parts[0].trim() to parts[1].trim())
                            }
                        }
                }
                !entry.isDirectory -> {
                    val outFile = File(targetDir, name)
                    // Security: block ZIP slip path traversal.
                    // Use canonical paths with explicit separator to prevent
                    // /prefix/usr-evil matching /prefix/usr boundary.
                    val canonical = outFile.canonicalPath
                    val targetCanonical = targetDir.canonicalPath
                    val isInTarget = canonical.startsWith(targetCanonical + File.separator) ||
                        canonical == targetCanonical
                    if (!isInTarget) {
                        Log.w(TAG, "Skipping path traversal entry: $name -> $canonical")
                        entry = zis.nextEntry
                        continue
                    }
                    outFile.parentFile?.mkdirs()

                    // Read into memory, patch com.termux→com.nvterm, write out.
                    // Same-length replacement (10 bytes each) — safe for ALL files
                    // including ELF binaries. Zero extra I/O passes.
                    val data = zis.readBytes()
                    val ext = outFile.extension.lowercase()
                    val shouldPatch = ext !in SKIP_PATCH_EXTENSIONS
                        && name !in SKIP_PATCH_FILES
                    if (shouldPatch) {
                        patchBytes(data, OLD_PKG_BYTES, NEW_PKG_BYTES)
                    }

                    // Rename termux-exec → nvterm-exec during extraction.
                    // Libraries, scripts, and binaries all get renamed for consistency.
                    // This provides forward-compatibility when we build our own packages.
                    // Note: termux-tools scripts (termux-setup-storage, etc.) are NOT renamed
                    // because apt packages depend on these exact filenames.
                    val finalFile = when {
                        outFile.name.startsWith("libtermux-exec") ->
                            File(outFile.parentFile, outFile.name.replace("libtermux-exec", "libnvterm-exec"))
                        outFile.name.startsWith("termux-exec-") ->
                            File(outFile.parentFile, outFile.name.replace("termux-exec-", "nvterm-exec-"))
                        outFile.name.startsWith("libtermux-core") ->
                            File(outFile.parentFile, outFile.name.replace("libtermux-core", "libnvterm-core"))
                        else -> outFile
                    }
                    finalFile.writeBytes(data)
                }
            }

            extracted++
            if (totalEntries > 0) {
                _state.value = State.Extracting(
                    progress = extracted.toFloat() / totalEntries,
                    currentFile = name.substringAfterLast('/'),
                )
            }

            entry = zis.nextEntry
        }

        Log.i(TAG, "Extracted $extracted files, found ${symlinks.size} symlinks")
    }

    // ── dpkg wrapper ──────────────────────────────────────

    /**
     * Install a dpkg wrapper that patches downloaded .deb files before
     * dpkg processes them. Termux repo .debs have paths with com.termux
     * hardcoded; we replace with com.nvterm (same length = safe binary sed).
     *
     * Strategy: rename real dpkg to dpkg.real, install a shell script as
     * dpkg that patches any .deb arguments, then calls dpkg.real.
     */
    private fun installDpkgWrapper(prefix: File) {
        val dpkgReal = File(prefix, "bin/dpkg.real")
        val dpkgBin = File(prefix, "bin/dpkg")

        // Only install once
        if (dpkgReal.exists()) return
        if (!dpkgBin.exists()) return

        // Rename real dpkg
        dpkgBin.renameTo(dpkgReal)

        // Write wrapper script — handles both direct .deb args and --recursive dirs
        // Also handles large packages (>50MB) via direct extraction fallback
        // Derive paths from the actual prefix to avoid hardcoding the package name.
        // prefix is already the usr dir (e.g. /data/data/com.nvterm/files/usr),
        // so binPath is prefix/bin and NVTERM_PREFIX is the parent (files dir).
        val prefixPath = prefix.absolutePath
        val binPath = "$prefixPath/bin"
        val filesPath = (prefix.parentFile ?: prefix).absolutePath
        dpkgBin.writeText(buildString {
            appendLine("#!$binPath/sh")
            appendLine("# NovaTerm dpkg wrapper — patches com.termux paths in .deb files")
            appendLine("# com.termux and com.nvterm are both 10 bytes → safe binary replacement")
            appendLine("# Real dpkg is at dpkg.real")
            appendLine()
            appendLine("DPKG_DEB=\"$binPath/dpkg-deb\"")
            appendLine("DPKG_REAL=\"$binPath/dpkg.real\"")
            appendLine("NVTERM_PREFIX=\"$filesPath\"")
            appendLine()
            appendLine("patch_deb() {")
            appendLine("  local deb=\"\$1\"")
            appendLine("  [ -f \"\$deb\" ] || return 0")
            appendLine("  # Skip if already patched or no com.termux paths")
            appendLine("  \$DPKG_DEB -c \"\$deb\" 2>/dev/null | grep -q \"com\\.termux\" || return 0")
            appendLine("  # Check package size — large packages (>50MB) use direct extraction")
            appendLine("  local size=\$(wc -c < \"\$deb\" 2>/dev/null || echo 0)")
            appendLine("  if [ \"\$size\" -gt 52428800 ]; then")
            appendLine("    # Large package: extract directly to prefix, skip rebuild")
            appendLine("    local tmp=\"\$(mktemp -d)\"")
            appendLine("    \$DPKG_DEB -x \"\$deb\" \"\$tmp\" 2>/dev/null || { rm -rf \"\$tmp\"; return 1; }")
            appendLine("    if [ -d \"\$tmp/data/data/com.termux/files\" ]; then")
            appendLine("      cp -a \"\$tmp/data/data/com.termux/files/.\" \"\$NVTERM_PREFIX/\" 2>/dev/null")
            appendLine("      # Patch text files in newly installed paths")
            appendLine("      find \"\$NVTERM_PREFIX\" -newer \"\$tmp\" -type f \\( -name '*.sh' -o -name '*.conf' -o -name '*.cfg' -o -name '*.properties' -o -name '*.xml' -o -name '*.policy' -o -name '*.txt' \\) \\")
            appendLine("        -exec sed -i 's/com\\.termux/com.nvterm/g' {} + 2>/dev/null")
            appendLine("    fi")
            appendLine("    rm -rf \"\$tmp\"")
            appendLine("    # Create a patched stub .deb so dpkg.real doesn't fail")
            appendLine("    local stub=\"\$(mktemp -d)\"")
            appendLine("    \$DPKG_DEB -e \"\$deb\" \"\$stub/DEBIAN\" 2>/dev/null")
            appendLine("    sed -i 's/com\\.termux/com.nvterm/g' \"\$stub/DEBIAN/control\" 2>/dev/null")
            appendLine("    mkdir -p \"\$stub/data/data/com.nvterm/files/usr\"")
            appendLine("    \$DPKG_DEB -b \"\$stub\" \"\$deb\" >/dev/null 2>&1")
            appendLine("    rm -rf \"\$stub\"")
            appendLine("    return 0")
            appendLine("  fi")
            appendLine("  # Normal package: extract, patch, rebuild")
            appendLine("  local tmp=\"\$(mktemp -d)\"")
            appendLine("  \$DPKG_DEB --raw-extract \"\$deb\" \"\$tmp/pkg\" 2>/dev/null || { rm -rf \"\$tmp\"; return 1; }")
            appendLine("  [ -d \"\$tmp/pkg/data/data/com.termux\" ] && mv \"\$tmp/pkg/data/data/com.termux\" \"\$tmp/pkg/data/data/com.nvterm\"")
            appendLine("  find \"\$tmp/pkg\" -type f -exec sed -i 's/com\\.termux/com.nvterm/g' {} + 2>/dev/null")
            appendLine("  \$DPKG_DEB -b \"\$tmp/pkg\" \"\$deb\" >/dev/null 2>&1")
            appendLine("  rm -rf \"\$tmp\"")
            appendLine("}")
            appendLine()
            appendLine("# Patch .deb files: handle both direct file args AND --recursive dirs")
            appendLine("for arg in \"\$@\"; do")
            appendLine("  case \"\$arg\" in")
            appendLine("    *.deb) patch_deb \"\$arg\" ;;")
            appendLine("    *) [ -d \"\$arg\" ] && for deb in \"\$arg\"/*.deb; do patch_deb \"\$deb\"; done ;;")
            appendLine("  esac")
            appendLine("done")
            appendLine()
            appendLine("exec \"\$DPKG_REAL\" \"\$@\"")
        })

        dpkgBin.setExecutable(true, true)
        dpkgBin.setReadable(true, true)
        Log.i(TAG, "Installed dpkg wrapper script")
    }

    /**
     * Clean up failed bootstrap installation by removing all installed files.
     * @param prefixDir The prefix directory to clean up
     */
    private fun cleanUpFailedBootstrap(prefixDir: String) {
        val prefix = File(prefixDir)
        if (prefix.exists()) {
            try {
                // Remove the entire prefix directory
                val oldPrefix = File(prefixDir + "-old")
                if (oldPrefix.exists()) {
                    oldPrefix.deleteRecursively()
                }
                prefix.deleteRecursively()
                Log.e(TAG, "Cleaned up failed bootstrap installation at $prefixDir")
            } catch (e: Exception) {
                Log.e(TAG, "Failed to clean up bootstrap: ${e.message}", e)
            }
        }
    }

    // ── Inline byte patching (during extraction) ───────────

    /**
     * Replace all occurrences of [old] with [new] in [data] in-place.
     * Both arrays MUST have equal length (same-length binary patching).
     */
    private fun patchBytes(data: ByteArray, old: ByteArray, new: ByteArray) {
        require(old.size == new.size) {
            "patchBytes: arrays must be equal length — old=${old.size}, new=${new.size}"
        }
        var i = 0
        while (i <= data.size - old.size) {
            var match = true
            for (j in old.indices) {
                if (data[i + j] != old[j]) { match = false; break }
            }
            if (match) {
                System.arraycopy(new, 0, data, i, new.size)
                i += new.size
            } else {
                i++
            }
        }
    }

    // ── Permissions ───────────────────────────────────

    private fun setExecutePermissions(prefix: File) {
        // Directories that contain executable files (walked recursively)
        val execDirs = listOf("bin", "libexec", "lib/apt/methods")
        for (dir in execDirs) {
            val d = File(prefix, dir)
            if (!d.isDirectory) continue
            d.walkTopDown().forEach { file ->
                if (file.isFile || java.nio.file.Files.isSymbolicLink(file.toPath())) {
                    file.setExecutable(true, true)  // owner-only
                    file.setReadable(true, true)
                    file.setWritable(true, true)
                }
            }
        }

        // Shared libraries also need execute permission
        prefix.walkTopDown()
            .filter { it.isFile && (it.name.endsWith(".so") || it.name.contains(".so.")) }
            .forEach { it.setExecutable(true, true) }
    }

    // ── Login script patching ─────────────────────────────

    /**
     * Patch the Termux login script to export TMPDIR early.
     * This is critical for Claude Code and other Node.js tools that
     * call os.tmpdir() which returns /tmp if TMPDIR is not set.
     * Android's /tmp is owned by shell:shell and not writable by apps.
     */
    private fun patchLoginScript(prefix: File) {
        val login = File(prefix, "bin/login")
        if (!login.exists()) return

        try {
            var content = login.readText()

            // Insert TMPDIR export right after the shebang line
            val shebang = content.lines().first()
            val rest = content.removePrefix(shebang).trimStart('\n')
            content = buildString {
                appendLine(shebang)
                appendLine()
                appendLine("# NovaTerm: ensure TMPDIR points to writable directory")
                appendLine("# Android's /tmp is not writable by apps (owned by shell:shell)")
                appendLine("export TMPDIR=\"\${TMPDIR:-\${PREFIX:-/data/data/com.nvterm/files/usr}/tmp}\"")
                appendLine("export TMP=\"\$TMPDIR\"")
                appendLine("export TEMP=\"\$TMPDIR\"")
                appendLine()
                append(rest)
            }

            login.writeText(content)
            login.setExecutable(true, true)
            Log.i(TAG, "Patched login script with TMPDIR export")
        } catch (e: Exception) {
            Log.w(TAG, "Failed to patch login script: ${e.message}")
        }
    }

    // ── MOTD branding ─────────────────────────────────────

    /** Replace Termux's default MOTD with NovaTerm branding. */
    private fun replaceMotd(prefix: File) {
        val motd = File(prefix, "etc/motd")
        try {
            motd.writeText(buildString {
                appendLine("Welcome to NovaTerm!")
                appendLine()
                appendLine("  Docs:     https://github.com/novaterm-org/NovaTerm")
                appendLine("  Packages: pkg install <name>")
                appendLine("  AI:       claude (Claude Code)")
                appendLine()
            })
            Log.i(TAG, "Replaced MOTD with NovaTerm branding")
        } catch (e: Exception) {
            Log.w(TAG, "Failed to replace MOTD: ${e.message}")
        }
    }

    // ── Asset scripts ─────────────────────────────────────

    /** Copy a script from APK assets to the prefix, with execute permission. */
    private fun copyAssetScript(assetName: String, dest: File) {
        try {
            context.assets.open(assetName).use { input ->
                dest.parentFile?.mkdirs()
                dest.outputStream().use { output -> input.copyTo(output) }
            }
            dest.setExecutable(true, true)
            dest.setReadable(true, true)
            Log.i(TAG, "Copied asset script: $assetName → ${dest.absolutePath}")
        } catch (e: Exception) {
            Log.w(TAG, "Failed to copy asset script: $assetName: ${e.message}")
        }
    }

    // ── Symlinks ──────────────────────────────────────────

    private fun createSymlinks(symlinks: List<Pair<String, String>>, prefix: File) {
        // Critical symlinks that must succeed for the terminal to work
        val criticalLinks = setOf("bin/sh", "bin/bash", "bin/login")
        var created = 0
        var failed = 0
        val criticalFailures = mutableListOf<String>()

        val prefixCanonical = prefix.canonicalPath + File.separator
        for ((target, linkPath) in symlinks) {
            try {
                val linkFile = File(prefix, linkPath)
                // Security: verify the link path stays within prefix (prevent path traversal via SYMLINKS.txt)
                val linkCanonicalParent = linkFile.parentFile?.canonicalPath ?: continue
                if (!linkCanonicalParent.startsWith(prefixCanonical) && linkCanonicalParent != prefix.canonicalPath) {
                    Log.w(TAG, "Symlink path escapes prefix, skipping: $linkPath")
                    failed++
                    continue
                }
                linkFile.parentFile?.mkdirs()
                linkFile.delete()
                Os.symlink(target, linkFile.absolutePath)
                created++
            } catch (e: Exception) {
                Log.w(TAG, "Symlink failed: $linkPath → $target: ${e.message}")
                failed++
                if (linkPath in criticalLinks) {
                    criticalFailures.add(linkPath)
                }
            }
        }
        Log.i(TAG, "Symlinks: $created created, $failed failed")
        if (criticalFailures.isNotEmpty()) {
            Log.e(TAG, "Critical symlinks failed: ${criticalFailures.joinToString()}")
        }
    }

    companion object {
        private const val TAG = "Bootstrap"

        // Same-length byte arrays for inline binary patching during extraction.
        // com.termux (10 bytes) == com.nvterm (10 bytes) — safe for ELF binaries.
        private val OLD_PKG_BYTES = "com.termux".toByteArray(Charsets.US_ASCII)
        private val NEW_PKG_BYTES = "com.nvterm".toByteArray(Charsets.US_ASCII)

        // Extensions containing crypto/compressed data — must NOT be patched.
        private val SKIP_PATCH_EXTENSIONS = setOf(
            "gpg", "pgp", "sig", "asc", "der", "pem", "crt", "key",
            "gz", "xz", "bz2", "zst", "lz4", "zip", "tar", "deb",
            "png", "jpg", "jpeg", "gif", "ico", "webp",
        )

        // Specific files that must NOT be patched (Java class names, etc.)
        private val SKIP_PATCH_FILES = setOf(
            "bin/am",                    // Java class: com.termux.termuxam.Am
            "libexec/termux-am/am.apk",  // APK with Java classes
            "lib/libtermux-exec.so",                          // Renamed to libnvterm-exec.so at extraction
            "lib/libtermux-exec-ld-preload.so",               // Renamed at extraction
            "lib/libtermux-exec-linker-ld-preload.so",        // Renamed at extraction
            "bin/termux-exec-ld-preload-lib",                // Renamed to nvterm-exec-ld-preload-lib
            "bin/termux-exec-system-linker-exec",              // Renamed to nvterm-exec-system-linker-exec
            "lib/libtermux-core_nos_c_tre.so",                // Renamed to libnvterm-core_nos_c_tre.so
            "lib/libtermux-core_nos_cxx_tre.so",               // Renamed to libnvterm-core_nos_cxx_tre.so
        )

        // Expected SHA-256 checksums for critical bootstrap files.
        // Placeholder "0000..." = not yet generated; falls back to existence + size check.
        // Run `scripts/generate_bootstrap_checksums.sh` on a device after first install,
        // then paste the output here. CI should automate this in the build pipeline.
        private val EXPECTED_CHECKSUMS = mapOf(
            "bin/bash" to "0000000000000000000000000000000000000000000000000000000000000000",
            "bin/sh" to "0000000000000000000000000000000000000000000000000000000000000000",
            "bin/login" to "0000000000000000000000000000000000000000000000000000000000000000",
            "lib/libnvterm-exec-linker-ld-preload.so" to "0000000000000000000000000000000000000000000000000000000000000000",
            "lib/libnvterm-exec-ld-preload.so" to "0000000000000000000000000000000000000000000000000000000000000000",
            "lib/libnvterm-exec.so" to "0000000000000000000000000000000000000000000000000000000000000000",
            "lib/libnvterm-core_nos_c_tre.so" to "0000000000000000000000000000000000000000000000000000000000000000",
            "lib/libnvterm-core_nos_cxx_tre.so" to "0000000000000000000000000000000000000000000000000000000000000000",
        )
    }
}

/**
 * JNI bridge to access the bootstrap ZIP embedded in the native library.
 * The ZIP is included via .incbin assembly directive in novaterm-bootstrap-zip.S.
 */
internal object NativeBootstrap {
    init {
        System.loadLibrary("novaterm-bootstrap")
    }

    @JvmStatic
    external fun getZip(): ByteArray
}
